Repository DataDog/datadog-ci, pull requests merged in 2024-10, with the labels that each got.

#1472 [STAL-2949] Make git author a mandatory field
  src/helpers/tags.ts
Labels: static-analysis

#1478 [SYNTH-16381] Add setCookies override
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/examples/global-config-complete-example.json
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1479 Add option to pass config shas manually on `correlate` command
  src/commands/deployment/README.md
  src/commands/deployment/__tests__/correlate.test.ts
  src/commands/deployment/correlate.ts
Labels: ci-visibility

#1480 [SYNTH-16456] Postpone reporting results on 404
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/api.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/interfaces.ts
Labels: synthetics

#1485 [SDCI] Remove correlate command flaky test
  src/commands/deployment/__tests__/correlate.test.ts
Labels: ci-visibility

#1484 v2.44.0
  package.json
Labels: release
