Repository DataDog/datadog-ci, pull requests merged in 2024-05, with the labels that each got.

#1298 [SYNTH-12976] Ignore default polling timeout in override count
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/reporters/default.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1275 Add elf symbols upload command
  .github/CODEOWNERS
  .github/advanced-issue-labeler.yml
  .github/release.yml
  .github/workflows/pr-required-labels.yml
  README.md
  src/cli.ts
  src/commands/dsyms/utils.ts
  src/commands/elf-symbols/README.md
  src/commands/elf-symbols/__tests__/elf.test.ts
  src/commands/elf-symbols/__tests__/fixtures/config/datadog-ci.json
  src/commands/elf-symbols/__tests__/fixtures/dyn_aarch64
  src/commands/elf-symbols/__tests__/fixtures/dyn_aarch64.debug
  src/commands/elf-symbols/__tests__/fixtures/dyn_aarch64_nobuildid
  src/commands/elf-symbols/__tests__/fixtures/dyn_x86_64
  src/commands/elf-symbols/__tests__/fixtures/exec_aarch64
  src/commands/elf-symbols/__tests__/fixtures/exec_arm_big
  src/commands/elf-symbols/__tests__/fixtures/exec_arm_little
  src/commands/elf-symbols/__tests__/fixtures/go_x86_64_both_gnu_and_go_build_id
  src/commands/elf-symbols/__tests__/fixtures/go_x86_64_only_go_build_id
  src/commands/elf-symbols/__tests__/fixtures/go_x86_64_only_go_build_id.debug
  src/commands/elf-symbols/__tests__/fixtures/non_elf_file
  src/commands/elf-symbols/__tests__/fixtures/truncated_elf_file
  src/commands/elf-symbols/__tests__/upload.test.ts
  src/commands/elf-symbols/cli.ts
  src/commands/elf-symbols/elf-constants.ts
  src/commands/elf-symbols/elf.ts
  src/commands/elf-symbols/helpers.ts
  src/commands/elf-symbols/interfaces.ts
  src/commands/elf-symbols/renderer.ts
  src/commands/elf-symbols/upload.ts
  src/helpers/utils.ts
Labels: profiling

#1144 [SCICM-1184] git sync is now available in Gov DC
  src/commands/git-metadata/upload.ts
Labels: source-code-integration

#1303 [git-metadata] Update command limitations
  src/commands/git-metadata/README.md
Labels: documentation

#1293 [SYNTH-12971] Make `executeTests` backwards compatible
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/test.test.ts
  src/commands/synthetics/api.ts
  src/commands/synthetics/compatibility.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/test.ts
Labels: synthetics

#1300 Add measures for custom commands
  src/commands/trace/interfaces.ts
  src/commands/trace/trace.ts
  src/helpers/tags.ts
Labels: ci-visibility

#1305 v2.35.0
  package.json
Labels: release

#1240 [SYNTH-12516][Mobile] Add new validation and custom reporter to mobile app uploads
  src/commands/synthetics/__tests__/api.test.ts
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/mobile.test.ts
  src/commands/synthetics/__tests__/reporters/mobile/__snapshots__/app-upload.test.ts.snap
  src/commands/synthetics/__tests__/reporters/mobile/app-upload.test.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/api.ts
  src/commands/synthetics/errors.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/mobile.ts
  src/commands/synthetics/reporters/constants.ts
  src/commands/synthetics/reporters/default.ts
  src/commands/synthetics/reporters/mobile/app-upload.ts
  src/commands/synthetics/upload-application-command.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1301 [SYNTH-14344] Do not require etag from app part upload
  src/commands/synthetics/__tests__/api.test.ts
  src/commands/synthetics/api.ts
Labels: synthetics

#1308 v2.36.0
  package.json
Labels: release

#1310 [dep] Bump `dd-trace`
  package.json
  yarn.lock
Labels: dependencies

#1306 [SYNTH-12972] Change `config` to `testOverrides`
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/mobile.test.ts
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/compatibility.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/mobile.ts
  src/commands/synthetics/reporters/default.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/test.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1311 Change the name of the describe block in mobile test
  src/commands/synthetics/__tests__/mobile.test.ts
Labels: synthetics

#1314 Remove SCA from GitHub action
  .github/workflows/ci.yml
Labels: chores

#1313 [ci] Change registry for docker image
  .gitlab-ci.yml
Labels: chores

#1312 RN: Override iOS upload version with ENV var
  src/commands/react-native/README.md
  src/commands/react-native/xcode.ts
Labels: rum

#1316 [SYNTH-12985] Add properties to env variables
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/upload-application-command.ts
  src/commands/synthetics/utils/internal.ts
Labels: synthetics

#1318 [lint] Fix semi-colon
  src/commands/react-native/xcode.ts
Labels: chores

#1315 [junit upload] Fix wrongly processed glob patterns
  .github/workflows/ci.yml
  .github/workflows/e2e/junit-reports/subfolder/junit-2.xml
  src/commands/junit/__tests__/fixtures/other/other-non-junit-file.txt
  src/commands/junit/__tests__/fixtures/subfolder/non-junit-file.txt
  src/commands/junit/__tests__/upload.test.ts
  src/commands/junit/upload.ts
Labels: ci-visibility

#1319 [codeowners] Add maintainer team everywhere
  .github/CODEOWNERS
Labels: chores

#1321 Remove unnecessary console.log in the `measure` command
  src/commands/measure/measure.ts
Labels: ci-visibility

#1323 Improve measure command error handling
  src/commands/measure/measure.ts
Labels: ci-visibility
