Repository DataDog/datadog-ci, pull requests merged in 2024-09, with the labels that each got.

#1431 [SYNTH-15922] Fix warning log about `pollingTimeout`
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/compatibility.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/run-tests-lib.ts
Labels: synthetics

#1433 [docs] Fix some instructions on test overrides
  src/commands/synthetics/README.md
Labels: documentation, synthetics

#1434 check rule existence in extensions
  src/commands/sarif/__tests__/fixtures/test_validation/rules-in-extensions.sarif
  src/commands/sarif/__tests__/validation.test.ts
  src/commands/sarif/validation.ts
Labels: static-analysis

#1432 Fix Step Functions context injection
  src/commands/stepfunctions/helpers.ts
Labels: serverless

#1441 [deployment] Fix error with `deployment mark`
  src/commands/deployment/__tests__/mark.test.ts
  src/commands/tag/tag.ts
Labels: ci-visibility

#1440 [SYNTH-15675] Report timed out retries
  src/commands/synthetics/__tests__/batch.test.ts
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/reporters/default.ts
  src/commands/synthetics/reporters/junit.ts
  src/commands/synthetics/utils/internal.ts
Labels: synthetics

#1452 [synthetics] Fix retry attempt wording
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/reporters/default.ts
Labels: synthetics

#1449 [dep] Bump `path-to-regexp` to `6.3.0`
  yarn.lock
Labels: dependencies

#1443 Print warning if traces merging is skipped for Lambda in Step Function
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: serverless, chores

#1437 Add explicit function return type for Lambda and Step Function code
  src/commands/lambda/flare.ts
  src/commands/lambda/functions/commons.ts
  src/commands/lambda/functions/instrument.ts
  src/commands/lambda/functions/uninstrument.ts
  src/commands/lambda/instrument.ts
  src/commands/lambda/loggroup.ts
  src/commands/lambda/prompt.ts
  src/commands/lambda/tags.ts
  src/commands/lambda/uninstrument.ts
  src/commands/stepfunctions/instrument.ts
  src/commands/stepfunctions/uninstrument.ts
Labels: serverless, chores

#1445 [ci-visibility] Show error message on deployment correlate command
  src/commands/deployment/__tests__/correlate.test.ts
  src/commands/deployment/correlate.ts
  src/commands/synthetics/__tests__/api.test.ts
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/__tests__/reporters/junit.test.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/helpers/__tests__/fixtures.ts
Labels: ci-visibility

#1446 [SYNTH-16168] Increase batch limit to 1000
  src/commands/synthetics/__tests__/utils/__snapshots__/public.test.ts.snap
  src/commands/synthetics/run-tests-command.ts
Labels: synthetics

#1448 [chore] Clean yarn resolutions
  LICENSE-3rdparty.csv
  package.json
  src/commands/lambda/__tests__/fixtures.ts
  yarn.lock
Labels: dependencies

#1447 Print warning if traces merging from xfn to xfn is skipped
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: serverless, chores

#1450 Skip xfn->Lambda context injection if custom Payload is used without $
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: enhancement, serverless

#1451 Skip xfn->xfn context injection if custom Payload is used without $
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: enhancement, serverless

#1455 Refactor step function code by flipping if-condition
  src/commands/stepfunctions/helpers.ts
Labels: serverless, chores

#1456 fix: print a better message if Step Function context injection is already set up
  src/commands/stepfunctions/helpers.ts
Labels: serverless, chores

#1454 v2.43.0
  package.json
Labels: release

#1458 fix: xfn context injection skipped if no update on last step
  src/commands/stepfunctions/helpers.ts
Labels: bug, serverless

#1459 Refactor xfn Lambda injection code my merging two functions
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: serverless, chores

#1460 Inject context for xfn->Lambda when no Payload exists (case 1)
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: enhancement, serverless

#1461 Skip xfn->Lambda context injection of Payload is not object (case 3)
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: enhancement, serverless

#1462 Handle sfn->Lambda context injection when Payload is used without $ (case 2)
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: enhancement, serverless

#1464 Remove beta flag from standalone binary
  README.md
Labels: documentation

#1453 Propagating CycloneDx information
  src/commands/sbom/__tests__/fixtures/sbom.1.5.ok.json
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/constants.ts
  src/commands/sbom/payload.ts
  src/commands/sbom/types.ts
Labels: static-analysis

#1466 Refactor sfn->sfn context injection code by merging two functions
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: serverless, chores

#1467 Refactor sfn->sfn context injection code by merging two functions (2)
  src/commands/stepfunctions/helpers.ts
Labels: serverless, chores

#1468 Support sfn->sfn context injection case 3
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: enhancement, serverless

#1470 Handle another case when sfn->Lambda context injection is already set…
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: enhancement, serverless

#1471 Revamp SFN->SFN context injection
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/helpers.ts
Labels: enhancement, serverless
