Repository DataDog/datadog-ci, pull requests merged in 2024-08, with the labels that each got.

#1398 Revert "[dep] Bump glob to `11.0.0` (#1381)"
  package.json
  src/commands/dsyms/__tests__/upload.test.ts
  src/commands/dsyms/__tests__/utils.test.ts
  src/commands/dsyms/upload.ts
  src/commands/elf-symbols/upload.ts
  src/commands/flutter-symbols/__tests__/upload.test.ts
  src/commands/flutter-symbols/upload.ts
  src/commands/junit/__tests__/upload.test.ts
  src/commands/junit/upload.ts
  src/commands/sarif/__tests__/upload.test.ts
  src/commands/sarif/upload.ts
  src/commands/sourcemaps/upload.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/utils/public.ts
  src/commands/unity-symbols/upload.ts
  yarn.lock
Labels: dependencies

#1399 v2.40.3
  package.json
Labels: release

#1245 [ci-visibility] Create deployment correlate subcommand
  README.md
  src/commands/deployment/README.md
  src/commands/deployment/__tests__/correlate.test.ts
  src/commands/deployment/cli.ts
  src/commands/deployment/correlate.ts
  src/helpers/git/get-git-data.ts
Labels: ci-visibility

#1401 Revert "[dep] Bump rimraf to `6.0.1` (#1382)"
  LICENSE-3rdparty.csv
  package.json
  src/commands/dsyms/utils.ts
  yarn.lock
Labels: dependencies

#1402 v2.41.0
  package.json
Labels: release

#1404 Add SARIF validation
  src/commands/sarif/__tests__/fixtures/test_validation/invalid-sarif-no-rule.sarif
  src/commands/sarif/__tests__/upload.test.ts
  src/commands/sarif/__tests__/validation.test.ts
  src/commands/sarif/renderer.ts
  src/commands/sarif/upload.ts
  src/commands/sarif/validation.ts
Labels: static-analysis

#1386 [SYNTH-15356] Wrong case with `--override` fails silently
  LICENSE-3rdparty.csv
  package.json
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/utils/internal.ts
  yarn.lock
Labels: bug, synthetics, chores

#1394 [SYNTH-12977] Reorder properties
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/compatibility.ts
  src/commands/synthetics/run-tests-command.ts
Labels: synthetics

#1408 Add option to remove ci tags
  src/commands/sarif/upload.ts
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/upload.ts
  src/helpers/__tests__/tags.test.ts
  src/helpers/tags.ts
Labels: bug, static-analysis

#1410 [SYNTH-12986] Mark runName as deprecated
  src/commands/synthetics/reporters/junit.ts
  src/commands/synthetics/run-tests-command.ts
Labels: synthetics

#1388 [PROF-10235] Add symbol source and filename to elf symbols metadata
  src/commands/elf-symbols/README.md
  src/commands/elf-symbols/__tests__/elf.test.ts
  src/commands/elf-symbols/__tests__/fixtures/exec_arm_little
  src/commands/elf-symbols/__tests__/upload.test.ts
  src/commands/elf-symbols/elf.ts
  src/commands/elf-symbols/helpers.ts
  src/commands/elf-symbols/interfaces.ts
  src/commands/elf-symbols/upload.ts
Labels: enhancement, profiling

#1411 Update README.md.
  src/commands/elf-symbols/README.md
Labels: documentation, profiling

#1412 remove service and env
  src/commands/sarif/README.md
  src/commands/sarif/upload.ts
  src/commands/sbom/README.md
  src/commands/sbom/upload.ts
Labels: static-analysis

#1418 [dep] Align `package.json` with `yarn.lock` for GCP packages
  package.json
  yarn.lock
Labels: dependencies

#1419 [SYNTH-15833] Use batch as source of truth for `hasResultPassed()`
  .github/workflows/ci.yml
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1421 [dep] Bump axios to `1.7.4`
  package.json
  src/commands/synthetics/__tests__/api.test.ts
  src/commands/synthetics/__tests__/fixtures.ts
  yarn.lock
Labels: dependencies

#1425 Show error message when payload is invalid
  src/commands/sbom/renderer.ts
  src/commands/sbom/upload.ts
Labels: static-analysis

#1427 [STAL-2160] Show message when default branch not found
  src/commands/sbom/renderer.ts
  src/commands/sbom/upload.ts
Labels: static-analysis

#1428 [SYNTH-15991] Trigger api fast-tests and retrieve results
  __synthetics__/apiTest.synthetics.json
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/api.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/utils/internal.ts
Labels: synthetics

#1426 [ci-visibility] Add `--tags-file` and `--measures-file` options
  src/commands/measure/README.md
  src/commands/measure/__tests__/fixtures/empty.json
  src/commands/measure/__tests__/fixtures/invalid.json
  src/commands/measure/__tests__/measure.test.ts
  src/commands/measure/measure.ts
  src/commands/tag/README.md
  src/commands/tag/__tests__/fixtures/empty.json
  src/commands/tag/__tests__/fixtures/invalid.json
  src/commands/tag/__tests__/tag.test.ts
  src/commands/tag/tag.ts
  src/helpers/__tests__/tags-fixtures/invalid/not-a-json.yaml
  src/helpers/__tests__/tags-fixtures/measures-mixed.json
  src/helpers/__tests__/tags-fixtures/measures-valid.json
  src/helpers/__tests__/tags-fixtures/tags-mixed.json
  src/helpers/__tests__/tags-fixtures/tags-valid.json
  src/helpers/__tests__/tags-fixtures/tags-with-nested-fields.json
  src/helpers/__tests__/tags.test.ts
  src/helpers/tags.ts
Labels: ci-visibility
