Repository DataDog/datadog-ci, pull requests merged in 2024-04, with the labels that each got.

#1270 [ci-visibility] Add silent option to tag command
  src/commands/deployment/mark.ts
  src/commands/tag/README.md
  src/commands/tag/__tests__/tag.test.ts
  src/commands/tag/tag.ts
Labels: ci-visibility

#1268 [dora] Fix typo in message
  src/commands/dora/renderer.ts
Labels: ci-visibility

#1271 [SYNTH-13771] Fix "No tests to run" not being shown anymore
  src/commands/synthetics/__tests__/test.test.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/test.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1269 [synthetics] Fix incomplete residual results message
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/batch.ts
Labels: synthetics

#1272 [synthetics] Improve warning for too many tests to trigger
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/test.test.ts
  src/commands/synthetics/__tests__/utils/__snapshots__/public.test.ts.snap
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/test.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1273 enable diff-aware and non-diff-aware
  .github/workflows/ci.yml
Labels: static-analysis

#1274 [STAL-1577] Improve SBOM/SARIF messaging
  src/commands/sarif/__tests__/upload.test.ts
  src/commands/sarif/renderer.ts
  src/commands/sarif/upload.ts
  src/commands/sbom/renderer.ts
  src/commands/sbom/upload.ts
Labels: static-analysis

#1277 v2.33.0
  package.json
Labels: release

#1278 [STAL-1744] Add new validation logic
  src/commands/sbom/__tests__/fixtures/random-data
  src/commands/sbom/__tests__/fixtures/sbom-no-component.json
  src/commands/sbom/__tests__/license.test.ts
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/__tests__/validation.test.ts
  src/commands/sbom/license.ts
  src/commands/sbom/payload.ts
  src/commands/sbom/upload.ts
  src/commands/sbom/validation.ts
Labels: static-analysis

#1279 Fix DD-EVP-ORIGIN header values
  src/commands/flutter-symbols/helpers.ts
  src/commands/git-metadata/library.ts
  src/commands/git-metadata/upload.ts
  src/commands/react-native/upload.ts
  src/commands/sourcemaps/upload.ts
  src/commands/unity-symbols/helpers.ts
Labels: rum

#1280 Prepare version v2.33.1
  package.json
Labels: release

#1285 [SYNTH-12971] Rename global to defaultTestOverrides
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/test.test.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/test.ts
Labels: synthetics

#1287 [git upload] Improvements to git upload and change junit git upload default
  src/commands/git-metadata/__tests__/gitdb.test.ts
  src/commands/git-metadata/gitdb.ts
  src/commands/junit/__tests__/upload.test.ts
  src/commands/junit/upload.ts
Labels: ci-visibility

#1286 [synthetics] Adjust selective re-run wording
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/reporters/default.ts
Labels: synthetics

#1288 v2.34.0
  package.json
Labels: release

#1291 [ci] Fix macOS jobs failing to download Node.js 14
  .github/workflows/ci.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/publish-release.yml
Labels: chores

#1290 DOCS-7748 Continuous Testing and CI/CD Configuration Edits
  README.md
  src/commands/synthetics/README.md
Labels: documentation

#1294 [chores] Remove old unused files
  LEGAL
  bin/prepend_license_header.sh
  tslint.json
Labels: chores
