Repository DataDog/datadog-ci, pull requests merged in 2024-06, with the labels that each got.

#1320 [SYNTH-12983] Add testOverrides properties to env variables
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/utils/internal.ts
Labels: synthetics

#1328 Explore .dot directories when uploading elf symbols
  src/commands/elf-symbols/__tests__/elf.test.ts
  src/commands/elf-symbols/__tests__/fixtures/.debug/dyn_aarch64.debug
  src/commands/elf-symbols/__tests__/upload.test.ts
  src/commands/elf-symbols/renderer.ts
  src/commands/elf-symbols/upload.ts
Labels: bug, profiling

#1329 DOCS-8127 Continuous Testing and CI/CD Configuration Edit
  src/commands/synthetics/README.md
Labels: documentation

#1331 [PROF-9872] Improve elf-symbols upload command
  src/commands/elf-symbols/__tests__/upload.test.ts
  src/commands/elf-symbols/renderer.ts
  src/commands/elf-symbols/upload.ts
Labels: profiling

#1335 [STAL-2267] Make version optional in SBOM
  src/commands/sbom/__tests__/fixtures/sbom-missing-version.json
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/payload.ts
  src/commands/sbom/types.ts
Labels: static-analysis

#1333 [ci] Add build job for Ubuntu ARM
  .github/workflows/ci.yml
  .github/workflows/publish-release.yml
  standalone-e2e/standalone-binary.test.ts
Labels: enhancement, chores

#1330 [SYNTH-12984] Add complex overrides to `--override` CLI argument
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/utils/internal.ts
Labels: synthetics

#1325 Add step function context to nested step function calls
  src/commands/stepfunctions/__tests__/helpers.test.ts
  src/commands/stepfunctions/__tests__/instrument.test.ts
  src/commands/stepfunctions/helpers.ts
  src/commands/stepfunctions/instrument.ts
Labels: enhancement, serverless

#1340 [synthetics] Parameterize unit tests for deprecated usages
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
Labels: synthetics

#1337 [dep] Bump @grpc/grpc-js to `1.10.9`
  yarn.lock
Labels: dependencies

#1342 [dep] Bump braces to `3.0.3`
  yarn.lock
Labels: dependencies

#1346 v2.38.0
  package.json
Labels: release

#1343 [SYNTH-14569] Send validator extracted-metadata for temporary apps
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/mobile.test.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/mobile.ts
Labels: synthetics

#1350 Add --propagate-upstream-trace to Step Function README
  src/commands/stepfunctions/README.md
Labels: documentation

#1348 [ci] Bring back x64 macOS binary
  .github/workflows/ci.yml
  .github/workflows/publish-release.yml
Labels: chores

#1353 v2.38.1
  package.json
Labels: release

#1354 [SYNTH-12982] Fix the usage of variableStrings
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics
