Repository DataDog/datadog-ci, pull requests merged in 2024-07, with the labels that each got.

#1360 [SYNTH-15171] Fix multiple test configs with same id bug
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/run-tests-lib.ts
Labels: synthetics

#1357 [SYNTH-9539] Report non-final attempts of a result
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/reporters/default.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1362 [SYNTH-15265] Fix resourceUrlSubstitutionRegexes override from cli
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/utils/internal.ts
Labels: synthetics

#1361 [gate evaluate] Add `options.pull_request_sha` to the `datadog-ci gate evaluate` payload
  src/commands/gate/__tests__/evaluate.test.ts
  src/commands/gate/api.ts
  src/commands/gate/evaluate.ts
  src/commands/gate/interfaces.ts
  src/helpers/ci.ts
  src/helpers/interfaces.ts
  src/helpers/tags.ts
  src/helpers/utils.ts
Labels: enhancement, ci-visibility

#1364 v2.39.0
  package.json
Labels: release

#1363 Fix download link for windows binaries
  README.md
Labels: documentation

#1284 [ci-visibility] remove Buddy from available CI providers
  src/commands/measure/__tests__/measure.test.ts
  src/commands/measure/measure.ts
  src/commands/tag/__tests__/tag.test.ts
  src/commands/tag/tag.ts
  src/helpers/__tests__/ci-env/buddy.json
  src/helpers/__tests__/ci.test.ts
  src/helpers/ci.ts
Labels: ci-visibility

#1365 [SYNTH-15150] Refactor and improve `override from config file < ENV < CLI` test
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/utils/internal.ts
Labels: synthetics

#1366 Add Buddy as supported CI provider back
  src/commands/tag/tag.ts
  src/helpers/__tests__/ci-env/azurepipelines.json
  src/helpers/__tests__/ci-env/bitbucket.json
  src/helpers/__tests__/ci-env/bitrise.json
  src/helpers/__tests__/ci-env/buddy.json
  src/helpers/__tests__/ci-env/buildkite.json
  src/helpers/__tests__/ci-env/circleci.json
  src/helpers/__tests__/ci-env/codefresh.json
  src/helpers/__tests__/ci-env/gitlab.json
  src/helpers/__tests__/ci-env/jenkins.json
  src/helpers/__tests__/ci-env/teamcity.json
  src/helpers/__tests__/ci-env/usersupplied.json
  src/helpers/ci.ts
Labels: ci-visibility

#1356 [SYNTH-10422] Rename `pollingTimeout` to `batchTimeout`
  .github/workflows/e2e/global.config.json
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
  src/commands/synthetics/__tests__/tunnel/websocket.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/compatibility.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/mobile.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/test.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1370 [ci-visibility] Prefix contains deployment with `pipeline` namespace
  src/commands/deployment/__tests__/mark.test.ts
  src/commands/deployment/constants.ts
Labels: ci-visibility

#1371 [pr-labels] Allow multiple labels on PRs
  .github/workflows/pr-required-labels.yml
Labels: chores

#1367 [SYNTH-13898] Inform when selective re-run is rate-limited
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/compatibility.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-lib.ts
Labels: synthetics

#1368 [SYNTH-12978] Clarify use of global configuration file in README
  .github/workflows/e2e/example-global-config.json
  src/commands/synthetics/README.md
Labels: documentation

#1373 [SYNTH-15150] Add the rest of the missing test cases
  src/commands/synthetics/__tests__/cli.test.ts
Labels: synthetics

#1372 [SYNTH-12978] Make improvements to the README
  src/commands/synthetics/README.md
  src/commands/synthetics/compatibility.ts
  src/commands/synthetics/examples/global-config-complete-example.json
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-command.ts
Labels: documentation, editorial review

#1369 [ci-visibility] Trace command: add support for Github, Gitlab, Azure, AWS and Buildkite
  src/commands/trace/README.md
  src/commands/trace/__tests__/trace.test.ts
  src/commands/trace/api.ts
  src/commands/trace/interfaces.ts
  src/commands/trace/trace.ts
  src/helpers/ci.ts
Labels: ci-visibility

#1385 v2.40.0
  package.json
Labels: release

#1384 [SYNTH-12979] Document the use of proxy
  src/commands/synthetics/README.md
Labels: documentation, synthetics

#1387 [ci-visibility] Fix bug on trace command URL
  src/commands/trace/trace.ts
Labels: ci-visibility

#1389 v2.40.1
  package.json
Labels: release

#1381 [dep] Bump glob to `11.0.0`
  package.json
  src/commands/dsyms/__tests__/upload.test.ts
  src/commands/dsyms/__tests__/utils.test.ts
  src/commands/dsyms/upload.ts
  src/commands/elf-symbols/upload.ts
  src/commands/flutter-symbols/__tests__/upload.test.ts
  src/commands/flutter-symbols/upload.ts
  src/commands/junit/__tests__/upload.test.ts
  src/commands/junit/upload.ts
  src/commands/sarif/__tests__/upload.test.ts
  src/commands/sarif/upload.ts
  src/commands/sourcemaps/upload.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/utils/public.ts
  src/commands/unity-symbols/__tests__/upload.test.ts
  src/commands/unity-symbols/upload.ts
  yarn.lock
Labels: dependencies

#1382 [dep] Bump rimraf to `6.0.1`
  LICENSE-3rdparty.csv
  package.json
  src/commands/dsyms/utils.ts
  yarn.lock
Labels: dependencies

#1392 [dep] Bump fast-xml-parser to `4.4.1`
  package.json
  yarn.lock
Labels: dependencies

#1393 [Synthetics] Hint the user on the missing scope in case of error
  src/commands/synthetics/__tests__/api.test.ts
  src/commands/synthetics/api.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1395 v2.40.2
  package.json
Labels: release

#1397 [dep] Upgrade google-auth-library to `9.12.0`
  package.json
  yarn.lock
Labels: dependencies
