Repository DataDog/datadog-ci, pull requests merged in 2024-03, with the labels that each got.

#1217 [chores] Update labels and setup automatic release notes
  .github/CODEOWNERS
  .github/advanced-issue-labeler.yml
  .github/workflows/pr-required-labels.yml
  .github/workflows/release.yml
Labels: chores

#1219 [chores] Improve release process
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
Labels: chores

#1223 [junit] Tolerate `--skip-git-metadata-upload` as boolean flag
  src/commands/junit/__tests__/upload.test.ts
  src/commands/junit/upload.ts
Labels: ci-visibility

#1225 [chores] Move `changelog` to `.github` folder
  .github/release.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/publish-release.yml
Labels: chores

#1226 [chores] Exclude `release` label from release notes
  .github/release.yml
  .github/workflows/pr-required-labels.yml
  CONTRIBUTING.md
Labels: chores

#1227 [chores] Add `needs:` to `npm-publish`
  .github/workflows/publish-release.yml
Labels: chores

#1228 [chores] Add missing `.exe` and fix release notes bug
  .github/workflows/publish-release.yml
Labels: chores

#1236 [dep] Upgrade axios to `1.6.8`
  package.json
  yarn.lock
Labels: dependencies

#1235 [STAL-1561] add .net support
  src/commands/sbom/language.ts
  src/commands/sbom/types.ts
Labels: static-analysis

#1237 v2.32.1
  package.json
Labels: release

#1241 [chores] Fix last nits about the release process
  .github/release.yml
  .github/workflows/publish-release.yml
Labels: chores

#1242 [dep] Bump `upload-artifact` github action
  .github/workflows/ci.yml
Labels: chores

#1246 Bundle React Native code when building debug app for iOS device
  src/commands/react-native/__tests__/xcode.test.ts
  src/commands/react-native/xcode.ts
Labels: rum

#1239 [SYNTH-13307] Add retries for 429
  src/commands/synthetics/__tests__/api.test.ts
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/api.ts
Labels: synthetics

#1234 [STAL-1559] [static-analysis] Add SBOM location
  src/commands/sbom/__tests__/fixtures/osv-scanner-files.json
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/license.ts
  src/commands/sbom/payload.ts
  src/commands/sbom/renderer.ts
  src/commands/sbom/types.ts
  src/commands/sbom/upload.ts
Labels: static-analysis

#1248 [docs] Instructions for creating new commands
  CONTRIBUTING.md
Labels: documentation

#1244 fix(sbom): detect npm from purl
  src/commands/sbom/__tests__/fixtures/cyclonedx-npm.json
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/language.ts
Labels: static-analysis

#1252 [synthetics] Move non-exported utils to `batch.ts`
  src/commands/synthetics/batch.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1254 [synthetics] Align README and reporter interface
  src/commands/synthetics/README.md
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/reporters/default.ts
Labels: synthetics

#1253 [synthetics] Change wording around selective re-run
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/reporters/default.ts
Labels: synthetics

#1258 [chores] Fix lint on main branch
  src/commands/sbom/__tests__/payload.test.ts
Labels: chores

#1251 [SYNTH-13138] Wait for each `ServerResult` to be available
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/batch.ts
Labels: synthetics

#1263 v2.32.2
  package.json
Labels: release

#1264 [chores] Fix link in release process
  .github/release.yml
  CONTRIBUTING.md
Labels: chores

#1259 [SYNTH-13724] Differentiate batch timeout and local deadline
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/errors.ts
  src/commands/synthetics/reporters/default.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1265 [source-code-integration] Set `apiKey` in logger
  src/commands/git-metadata/upload.ts
Labels: source-code-integration

#1266 v2.32.3
  package.json
Labels: release

#1255 [SYNTH-12914] Include `?batch_id` in result links
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/__tests__/reporters/junit.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/reporters/default.ts
  src/commands/synthetics/reporters/junit.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics
