Repository DataDog/datadog-ci, pull requests merged in 2024-11, with the labels that each got.

#1489 [STAL-3155] Specify which git tags are missing
  src/commands/sarif/renderer.ts
  src/commands/sarif/upload.ts
  src/commands/sbom/renderer.ts
  src/commands/sbom/upload.ts
  src/helpers/tags.ts
Labels: static-analysis

#1490 v2.45.0
  package.json
Labels: release

#1487 Remove git checks in SBOM payload generation
  src/commands/sbom/payload.ts
Labels: enhancement, static-analysis, chores

#1494 [SYNTH-16911] Trigger batch with LTDs
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/__tests__/reporters/junit.test.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/reporters/default.ts
  src/commands/synthetics/reporters/junit.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/test.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics
