Repository DataDog/datadog-ci, pull requests merged in 2024-12, with the labels that each got.

#1499 [K9VULN-1175] Validate purl
  LICENSE-3rdparty.csv
  package.json
  src/commands/sbom/__tests__/fixtures/sbom-invalid-purl.json
  src/commands/sbom/__tests__/validation.test.ts
  src/commands/sbom/upload.ts
  src/commands/sbom/validation.ts
  yarn.lock
Labels: static-analysis

#1501 add a fips option to all existing commands
  .github/workflows/ci.yml
  .github/workflows/publish-release.yml
  README.md
  package.json
  src/__tests__/cli.test.ts
  src/commands/cloud-run/flare.ts
  src/commands/deployment/correlate.ts
  src/commands/deployment/mark.ts
  src/commands/dora/deployment.ts
  src/commands/dsyms/upload.ts
  src/commands/elf-symbols/upload.ts
  src/commands/flutter-symbols/upload.ts
  src/commands/gate/evaluate.ts
  src/commands/git-metadata/upload.ts
  src/commands/junit/upload.ts
  src/commands/lambda/flare.ts
  src/commands/lambda/instrument.ts
  src/commands/lambda/uninstrument.ts
  src/commands/measure/measure.ts
  src/commands/react-native/codepush.ts
  src/commands/react-native/upload.ts
  src/commands/react-native/xcode.ts
  src/commands/sarif/upload.ts
  src/commands/sbom/upload.ts
  src/commands/sourcemaps/upload.ts
  src/commands/stepfunctions/instrument.ts
  src/commands/stepfunctions/uninstrument.ts
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/upload-application-command.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/tag/tag.ts
  src/commands/trace/trace.ts
  src/commands/unity-symbols/upload.ts
  src/constants.ts
  src/helpers/__tests__/env.test.ts
  src/helpers/__tests__/fips.test.ts
  src/helpers/env.ts
  src/helpers/fips.ts
  yarn.lock
Labels: documentation, rum, synthetics, ci-visibility, serverless, source-code-integration, static-analysis, profiling

#1508 v2.46.1
  package.json
Labels: release

#1509 [chores] Adjustments in release process
  CONTRIBUTING.md
Labels: chores
