Repository DataDog/datadog-ci, pull requests merged in 2025-05, with the labels that each got.

#1634 v3.5.0
  package.json
Labels: release

#1636 Fix error message typo.
  src/commands/unity-symbols/renderer.ts
Labels: rum, mergequeue-status: in_progress

#1637 [docs] Update synthetics upload section + add partial comments
  src/commands/synthetics/README.md
Labels: synthetics

#1639 Escape Details URL in Quality Gates Response
  src/commands/gate/renderer.ts
Labels: ci-visibility, static-analysis, mergequeue-status: in_progress

#1640 Update coverage upload command to include git diff data
  src/commands/coverage/README.md
  src/commands/coverage/api.ts
  src/commands/coverage/interfaces.ts
  src/commands/coverage/upload.ts
  src/commands/git-metadata/__tests__/fixtures/add_delete.diff
  src/commands/git-metadata/__tests__/fixtures/modify_single_file.diff
  src/commands/git-metadata/__tests__/git.test.ts
  src/commands/git-metadata/git.ts
  src/helpers/__tests__/ci.test.ts
  src/helpers/ci.ts
  src/helpers/interfaces.ts
  src/helpers/tags.ts
  src/helpers/utils.ts
Labels: ci-visibility

#1642 [synthetics] Fix output of mobile app upload command
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/upload-application-command.ts
Labels: synthetics

#1645 v3.6.1
  package.json
Labels: release

#1648 [K9VULN-4956] Update text when unable to infer default branch
  src/commands/sbom/README.md
  src/commands/sbom/renderer.ts
Labels: static-analysis

#1647 [K9VULN-5404] Update duplicate upload notice
  src/commands/sbom/renderer.ts
  src/commands/sbom/upload.ts
Labels: static-analysis, mergequeue-status: in_progress

#1650 Add base and head SHAs to git diff data uploaded with coverage
  src/commands/coverage/api.ts
  src/commands/coverage/interfaces.ts
  src/commands/coverage/upload.ts
  src/commands/git-metadata/__tests__/git.test.ts
  src/commands/git-metadata/git.ts
Labels: ci-visibility

#1651 Rename PR ID tag to PR number
  src/helpers/__tests__/ci.test.ts
  src/helpers/ci.ts
  src/helpers/interfaces.ts
  src/helpers/tags.ts
Labels: ci-visibility

#1652 v3.7.0
  package.json
Labels: release
