Repository DataDog/datadog-ci, pull requests merged in 2025-01, with the labels that each got.

#1512 [K9VULN-2465] Add validation of package names
  src/commands/sbom/__tests__/validation.test.ts
  src/commands/sbom/payload.ts
  src/commands/sbom/renderer.ts
  src/commands/sbom/upload.ts
  src/commands/sbom/validation.ts
Labels: static-analysis

#1514 [K9VULN-2266] Support `is-dev` property from `osv-scanner`
  src/commands/sbom/__tests__/fixtures/sbom.1.5.ok.json
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/constants.ts
  src/commands/sbom/payload.ts
  src/commands/sbom/types.ts
Labels: static-analysis

#1515 [SYNTH-17698] Fix local test definition variable case
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/test.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1513 [K9VULN-2435] Add support for Cyclone DX 1.6
  src/commands/sbom/__tests__/fixtures/cdxgen-cyclonedx1.6.json
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/__tests__/validation.test.ts
  src/commands/sbom/json-schema/cyclonedx/bom-1.6.schema.json
  src/commands/sbom/payload.ts
  src/commands/sbom/validation.ts
Labels: static-analysis

#1516 [K9VULN] Specify `is_dev` in tests
  src/commands/sbom/__tests__/validation.test.ts
Labels: static-analysis

#1518 Change Serverless team in CODEOWNERS
  .github/CODEOWNERS
Labels: documentation, serverless

#1519 v2.47.0
  package.json
Labels: release

#1522 [docs] More info about `testSearchQuery`
  src/commands/synthetics/README.md
Labels: documentation, synthetics

#1526 SBOM: update licenses and filter invalid `purl`
  src/commands/sbom/__tests__/fixtures/sbom-invalid-purl.json
  src/commands/sbom/__tests__/validation.test.ts
  src/commands/sbom/json-schema/spdx/spdx.schema.json
  src/commands/sbom/language.ts
  src/commands/sbom/renderer.ts
  src/commands/sbom/upload.ts
  src/commands/sbom/validation.ts
Labels: static-analysis

#1527 Update code ownership
  .github/CODEOWNERS
Labels: static-analysis

#1528 v2.48.0
  package.json
Labels: release

#1523 [SYNTH-17721] Import LTD from a main test
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/import-tests-config-with-all-keys.json
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/import-tests-lib.test.ts
  src/commands/synthetics/api.ts
  src/commands/synthetics/cli.ts
  src/commands/synthetics/import-tests-command.ts
  src/commands/synthetics/import-tests-lib.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/reporters/junit.ts
  src/commands/synthetics/test.ts
Labels: synthetics

#1532 [K9VULN-3031] remove service flag
  src/commands/sarif/README.md
  src/commands/sarif/__tests__/upload.test.ts
  src/commands/sarif/api.ts
  src/commands/sarif/interfaces.ts
  src/commands/sarif/renderer.ts
  src/commands/sarif/upload.ts
  src/commands/sbom/README.md
  src/commands/sbom/upload.ts
Labels: static-analysis
