Repository DataDog/datadog-ci, pull requests merged in 2025-08, with the labels that each got.

#1797 [dep] Downgrade @azure/identity from to `4.10.2` to `4.10.1`
  package.json
  yarn.lock
Labels: dependencies

#1794 [SCICM-4946] Rollback "Escape Details URL in Quality Gates Response"
  src/commands/gate/renderer.ts
Labels: bug, ci-visibility

#1798 v3.18.0
  package.json
Labels: release

#1800 [Cloud Run] Add DD_SERVERLESS_LOG_PATH to app containers
  src/commands/cloud-run/__tests__/__snapshots__/instrument.test.ts.snap
  src/commands/cloud-run/instrument.ts
Labels: serverless

#1805 Add --base-path parameter to coverage upload command
  src/commands/coverage/README.md
  src/commands/coverage/__tests__/api.test.ts
  src/commands/coverage/__tests__/upload.test.ts
  src/commands/coverage/api.ts
  src/commands/coverage/interfaces.ts
  src/commands/coverage/renderer.ts
  src/commands/coverage/upload.ts
Labels: ci-visibility

#1807 [dep] Bump `google-auth-library` to 10.2.1
  package.json
  src/commands/cloud-run/__tests__/flare.test.ts
  src/commands/cloud-run/utils.ts
  yarn.lock
Labels: dependencies

#1809 v3.19.0
  package.json
Labels: release

#1814 Replace monitors_variable with monitors_query_variable in deployment gate command
  src/commands/deployment/__tests__/gate.test.ts
  src/commands/deployment/api.ts
  src/commands/deployment/gate.ts
  src/commands/deployment/interfaces.ts
Labels: ci-visibility

#1813 [synthetics] Add `ci.job.id` and `DD_CI_JOB_ID` override
  src/helpers/__tests__/ci.test.ts
  src/helpers/__tests__/user-provided-git.test.ts
  src/helpers/ci.ts
  src/helpers/interfaces.ts
  src/helpers/user-provided-git.ts
Labels: synthetics
