Repository DataDog/datadog-ci, pull requests merged in 2025-09, with the labels that each got.

#1819 Cloud Run Instrument Language Flag
  packages/datadog-ci/src/commands/cloud-run/README.md
  packages/datadog-ci/src/commands/cloud-run/__tests__/instrument.test.ts
  packages/datadog-ci/src/commands/cloud-run/instrument.ts
  packages/datadog-ci/src/constants.ts
Labels: serverless

#1823 Fix isFile utility method to handle symlinks
  packages/datadog-ci/src/helpers/__tests__/utils-fixtures/file-symlink.txt
  packages/datadog-ci/src/helpers/__tests__/utils-fixtures/file.txt
  packages/datadog-ci/src/helpers/__tests__/utils-fixtures/folder-symlink
  packages/datadog-ci/src/helpers/__tests__/utils.test.ts
  packages/datadog-ci/src/helpers/utils.ts
Labels: software-delivery

#1820 [chore] Use `knip` to remove leftover dependencies
  LICENSE-3rdparty.csv
  package.json
  packages/base/package.json
  packages/datadog-ci/package.json
  yarn.lock
Labels: chores, guild-project

#1822 [chore] Migrate to ESLint 9
  .eslintrc.js
  LICENSE-3rdparty.csv
  eslint.config.mjs
  jest.config-standalone.mjs
  jest.config-windows.mjs
  jest.config.mjs
  package.json
  packages/base/package.json
  packages/base/src/constants.ts
  packages/base/src/helpers/git/format-git-sourcemaps-data.ts
  packages/base/src/helpers/utils.ts
  packages/datadog-ci/package.json
  packages/datadog-ci/src/commands/cloud-run/__tests__/utils.test.ts
  packages/datadog-ci/src/commands/deployment/gate.ts
  packages/datadog-ci/src/commands/elf-symbols/elf-constants.ts
  packages/datadog-ci/src/commands/elf-symbols/elf.ts
  packages/datadog-ci/src/commands/elf-symbols/upload.ts
  packages/datadog-ci/src/commands/flutter-symbols/__tests__/upload.test.ts
  packages/datadog-ci/src/commands/flutter-symbols/upload.ts
  packages/datadog-ci/src/commands/git-metadata/__tests__/gitdb.test.ts
  packages/datadog-ci/src/commands/pe-symbols/pe.ts
  packages/datadog-ci/src/commands/pe-symbols/upload.ts
  packages/datadog-ci/src/commands/react-native/__tests__/inject-debug-id.test.ts
  packages/datadog-ci/src/commands/sourcemaps/utils.ts
  packages/datadog-ci/src/commands/unity-symbols/__tests__/upload.test.ts
  packages/datadog-ci/src/commands/unity-symbols/upload.ts
  packages/plugin-synthetics/package.json
  packages/plugin-synthetics/src/build-and-test.ts
  packages/plugin-synthetics/src/errors.ts
  packages/plugin-synthetics/src/interfaces.ts
  packages/plugin-synthetics/src/utils/internal.ts
  yarn.lock
Labels: chores, guild-project

#1821 [chore] Use source files during development for better DevX
  .eslintrc.js
  .github/workflows/ci.yml
  .github/workflows/publish-release.yml
  CONTRIBUTING.md
  LICENSE-3rdparty.csv
  eslint.config.mjs
  jest.config-standalone.mjs
  jest.config-windows.mjs
  jest.config.mjs
  package.json
  packages/base/package.json
  packages/base/src/constants.ts
  packages/base/src/helpers/git/format-git-sourcemaps-data.ts
  packages/base/src/helpers/utils.ts
  packages/base/tsconfig.json
  packages/datadog-ci/package.json
  packages/datadog-ci/src/commands/cloud-run/__tests__/utils.test.ts
  packages/datadog-ci/src/commands/deployment/gate.ts
  packages/datadog-ci/src/commands/elf-symbols/elf-constants.ts
  packages/datadog-ci/src/commands/elf-symbols/elf.ts
  packages/datadog-ci/src/commands/elf-symbols/upload.ts
  packages/datadog-ci/src/commands/flutter-symbols/__tests__/upload.test.ts
  packages/datadog-ci/src/commands/flutter-symbols/upload.ts
  packages/datadog-ci/src/commands/git-metadata/__tests__/gitdb.test.ts
  packages/datadog-ci/src/commands/pe-symbols/pe.ts
  packages/datadog-ci/src/commands/pe-symbols/upload.ts
  packages/datadog-ci/src/commands/react-native/__tests__/inject-debug-id.test.ts
  packages/datadog-ci/src/commands/sourcemaps/utils.ts
  packages/datadog-ci/src/commands/unity-symbols/__tests__/upload.test.ts
  packages/datadog-ci/src/commands/unity-symbols/upload.ts
  packages/datadog-ci/tsconfig.json
  packages/plugin-synthetics/package.json
  packages/plugin-synthetics/src/build-and-test.ts
  packages/plugin-synthetics/src/errors.ts
  packages/plugin-synthetics/src/interfaces.ts
  packages/plugin-synthetics/src/utils/internal.ts
  packages/plugin-synthetics/tsconfig.json
  standalone-e2e/tsconfig.json
  tsconfig.base.json
  tsconfig.json
  yarn.lock
Labels: chores, guild-project

#1839 [dep] Bump axios to `1.12.1`
  packages/base/package.json
  packages/datadog-ci/package.json
  packages/plugin-synthetics/package.json
  yarn.lock
Labels: dependencies

#1840 [SYNTH-21715] Create sbom package
  .github/CODEOWNERS
  .github/workflows/ci.yml
  README.md
  packages/base/package.json
  packages/base/src/cli.ts
  packages/base/src/commands/sbom/upload-command.ts
  packages/datadog-ci/package.json
  packages/datadog-ci/src/commands/sbom/cli.ts
  packages/datadog-ci/tsconfig.json
  packages/plugin-sbom/README.md
  packages/plugin-sbom/package.json
  packages/plugin-sbom/src/__tests__/fixtures/cdxgen-cyclonedx1.6.json
  packages/plugin-sbom/src/__tests__/fixtures/cyclonedx-npm.json
  packages/plugin-sbom/src/__tests__/fixtures/gitconfig
  packages/plugin-sbom/src/__tests__/fixtures/osv-scanner-files.json
  packages/plugin-sbom/src/__tests__/fixtures/random-data
  packages/plugin-sbom/src/__tests__/fixtures/sbom-invalid-purl.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom-java-go.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom-missing-version.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom-no-components.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom-python.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom-ruby.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom-rust.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom-with-exclusion.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom-with-reachability.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom.1.4.invalid.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom.1.4.ok-without-metadata.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom.1.4.ok.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom.1.5.ok-with-tools-as-components.json
  packages/plugin-sbom/src/__tests__/fixtures/sbom.1.5.ok.json
  packages/plugin-sbom/src/__tests__/fixtures/trivy-4.9.json
  packages/plugin-sbom/src/__tests__/language.test.ts
  packages/plugin-sbom/src/__tests__/payload.test.ts
  packages/plugin-sbom/src/__tests__/validation.test.ts
  packages/plugin-sbom/src/api.ts
  packages/plugin-sbom/src/cli.ts
  packages/plugin-sbom/src/commands/upload.ts
  packages/plugin-sbom/src/constants.ts
  packages/plugin-sbom/src/json-schema/cyclonedx/bom-1.4.schema.json
  packages/plugin-sbom/src/json-schema/cyclonedx/bom-1.5.schema.json
  packages/plugin-sbom/src/json-schema/cyclonedx/bom-1.6.schema.json
  packages/plugin-sbom/src/json-schema/jsf/jsf-0.82.schema.json
  packages/plugin-sbom/src/json-schema/spdx/spdx.schema.json
  packages/plugin-sbom/src/language.ts
  packages/plugin-sbom/src/payload.ts
  packages/plugin-sbom/src/renderer.ts
  packages/plugin-sbom/src/types.ts
  packages/plugin-sbom/src/validation.ts
  packages/plugin-sbom/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: static-analysis, guild-project

#1841 [SYNTH-21714] Create sarif package
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .gitignore
  README.md
  packages/base/package.json
  packages/base/src/cli.ts
  packages/base/src/commands/sarif/upload-command.ts
  packages/datadog-ci/package.json
  packages/datadog-ci/src/commands/sarif/cli.ts
  packages/datadog-ci/tsconfig.json
  packages/plugin-sarif/README.md
  packages/plugin-sarif/package.json
  packages/plugin-sarif/src/__tests__/fixtures/another_subfolder/valid-results.sarif
  packages/plugin-sarif/src/__tests__/fixtures/datadog-sa-only.json
  packages/plugin-sarif/src/__tests__/fixtures/datadog-sa-secrets.json
  packages/plugin-sarif/src/__tests__/fixtures/datadog-secrets-only-empty.json
  packages/plugin-sarif/src/__tests__/fixtures/empty.sarif
  packages/plugin-sarif/src/__tests__/fixtures/gitconfig
  packages/plugin-sarif/src/__tests__/fixtures/invalid-result.sarif
  packages/plugin-sarif/src/__tests__/fixtures/invalid.sarif
  packages/plugin-sarif/src/__tests__/fixtures/subfolder/valid-results.sarif
  packages/plugin-sarif/src/__tests__/fixtures/test_validation/invalid-sarif-no-rule.sarif
  packages/plugin-sarif/src/__tests__/fixtures/test_validation/rules-in-extensions.sarif
  packages/plugin-sarif/src/__tests__/fixtures/valid-no-results.sarif
  packages/plugin-sarif/src/__tests__/fixtures/valid-results.sarif
  packages/plugin-sarif/src/__tests__/upload.test.ts
  packages/plugin-sarif/src/__tests__/utils.test.ts
  packages/plugin-sarif/src/__tests__/validation.test.ts
  packages/plugin-sarif/src/api.ts
  packages/plugin-sarif/src/cli.ts
  packages/plugin-sarif/src/commands/upload.ts
  packages/plugin-sarif/src/interfaces.ts
  packages/plugin-sarif/src/json-schema/sarif-schema-2.1.0.json
  packages/plugin-sarif/src/renderer.ts
  packages/plugin-sarif/src/utils.ts
  packages/plugin-sarif/src/validation.ts
  packages/plugin-sarif/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: static-analysis, guild-project

#1843 Run yarn to fix broken pipelines
  yarn.lock
Labels: bug, datadog-ci

#1848 [SVLS] fix aas path mappings
  packages/base/src/cli.ts
  packages/plugin-aas/src/__tests__/instrument.test.ts
  packages/plugin-aas/src/__tests__/uninstrument.test.ts
  packages/plugin-aas/src/cli.ts
  packages/plugin-aas/src/commands/instrument.ts
  packages/plugin-aas/src/commands/uninstrument.ts
Labels: chores

#1844 [PACKAGES-MIGRATION] migrate cloud-run
  .github/CODEOWNERS
  .github/workflows/ci.yml
  jest.config-windows.mjs
  jest.config.mjs
  packages/base/package.json
  packages/base/src/cli.ts
  packages/base/src/commands/cloud-run/constants.ts
  packages/base/src/commands/cloud-run/flare.ts
  packages/base/src/commands/cloud-run/instrument.ts
  packages/base/src/commands/cloud-run/uninstrument.ts
  packages/base/src/helpers/__tests__/flare.test.ts
  packages/base/src/helpers/flare.ts
  packages/datadog-ci/package.json
  packages/datadog-ci/src/commands/cloud-run/cli.ts
  packages/datadog-ci/src/commands/lambda/__tests__/flare.test.ts
  packages/datadog-ci/src/commands/lambda/flare.ts
  packages/datadog-ci/tsconfig.json
  packages/plugin-cloud-run/README.md
  packages/plugin-cloud-run/package.json
  packages/plugin-cloud-run/src/__tests__/__snapshots__/flare.test.ts.snap
  packages/plugin-cloud-run/src/__tests__/__snapshots__/instrument.test.ts.snap
  packages/plugin-cloud-run/src/__tests__/__snapshots__/uninstrument.test.ts.snap
  packages/plugin-cloud-run/src/__tests__/flare.test.ts
  packages/plugin-cloud-run/src/__tests__/instrument.test.ts
  packages/plugin-cloud-run/src/__tests__/uninstrument.test.ts
  packages/plugin-cloud-run/src/__tests__/utils.test.ts
  packages/plugin-cloud-run/src/cli.ts
  packages/plugin-cloud-run/src/commands/flare.ts
  packages/plugin-cloud-run/src/commands/instrument.ts
  packages/plugin-cloud-run/src/commands/uninstrument.ts
  packages/plugin-cloud-run/src/interfaces.ts
  packages/plugin-cloud-run/src/prompt.ts
  packages/plugin-cloud-run/src/renderer.ts
  packages/plugin-cloud-run/src/types.ts
  packages/plugin-cloud-run/src/utils.ts
  packages/plugin-cloud-run/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: chores

#1852 [PACKAGES-MIGRATION] Migrate tag command to base package
  .github/CODEOWNERS
  packages/base/src/cli.ts
  packages/base/src/commands/tag/README.md
  packages/base/src/commands/tag/__tests__/fixtures/empty.json
  packages/base/src/commands/tag/__tests__/fixtures/invalid.json
  packages/base/src/commands/tag/__tests__/tag.test.ts
  packages/base/src/commands/tag/cli.ts
  packages/base/src/commands/tag/tag-command.ts
  packages/datadog-ci/src/__tests__/cli.test.ts
  packages/datadog-ci/src/commands/deployment/mark.ts
  packages/datadog-ci/src/commands/tag/cli.ts
Labels: software-delivery

#1854 [PACKAGES-MIGRATION] Migrate dora scope into a plugin
  .github/CODEOWNERS
  .github/workflows/ci.yml
  bin/migrate.sh
  packages/base/package.json
  packages/base/src/cli.ts
  packages/base/src/commands/dora/deployment-command.ts
  packages/datadog-ci/package.json
  packages/datadog-ci/src/commands/dora/cli.ts
  packages/datadog-ci/tsconfig.json
  packages/plugin-dora/README.md
  packages/plugin-dora/package.json
  packages/plugin-dora/src/__tests__/deployment.test.ts
  packages/plugin-dora/src/api.ts
  packages/plugin-dora/src/cli.ts
  packages/plugin-dora/src/commands/deployment.ts
  packages/plugin-dora/src/interfaces.ts
  packages/plugin-dora/src/renderer.ts
  packages/plugin-dora/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: software-delivery

#1828 [PACKAGES-MIGRATION] Move 'gate' commands to packages/gate
  .github/CODEOWNERS
  .github/workflows/ci.yml
  README.md
  packages/base/package.json
  packages/base/src/cli.ts
  packages/base/src/commands/gate/evaluate-command.ts
  packages/datadog-ci/package.json
  packages/datadog-ci/src/commands/gate/cli.ts
  packages/datadog-ci/tsconfig.json
  packages/plugin-gate/README.md
  packages/plugin-gate/package.json
  packages/plugin-gate/src/__tests__/evaluate.test.ts
  packages/plugin-gate/src/__tests__/scope.test.ts
  packages/plugin-gate/src/api.ts
  packages/plugin-gate/src/cli.ts
  packages/plugin-gate/src/commands/evaluate.ts
  packages/plugin-gate/src/interfaces.ts
  packages/plugin-gate/src/renderer.ts
  packages/plugin-gate/src/utils.ts
  packages/plugin-gate/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: chores, guild-project

#1858 [chore] Decrease standalone binary size
  .github/workflows/ci.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/publish-release.yml
  .yarn/patches/@yao-pkg-pkg-fetch-npm-3.5.24-3b96980136.patch
  .yarn/patches/@yao-pkg-pkg-npm-6.6.0-d4777368b9.patch
  bin/compare-binary-size.js
  eslint.config.mjs
  package.json
  packages/datadog-ci/scripts/esbuild.mjs
  packages/datadog-ci/shims/intl-collator.js
  yarn.lock
Labels: datadog-ci, guild-project

#1857 [chore] Mark `peerDependencies` in base package as optional
  bin/migrate.sh
  packages/base/package.json
  packages/plugin-dora/package.json
  packages/plugin-gate/package.json
  packages/plugin-lambda/package.json
  packages/plugin-stepfunctions/package.json
  packages/plugin-stepfunctions/src/__tests__/helpers.test.ts
  packages/plugin-stepfunctions/src/awsCommands.ts
  packages/plugin-stepfunctions/src/helpers.ts
  yarn.lock
Labels: chores, guild-project

#1861 v3.21.0
  packages/base/package.json
  packages/datadog-ci/package.json
  packages/plugin-aas/package.json
  packages/plugin-cloud-run/package.json
  packages/plugin-dora/package.json
  packages/plugin-gate/package.json
  packages/plugin-lambda/package.json
  packages/plugin-sarif/package.json
  packages/plugin-sbom/package.json
  packages/plugin-stepfunctions/package.json
  packages/plugin-synthetics/package.json
Labels: release

#1863 [chore] Fix release `3.21.0`
  .github/workflows/publish-prerelease.yml
  .github/workflows/publish-release.yml
  bin/migrate.sh
  package.json
  packages/base/README.md
  packages/base/package.json
  packages/datadog-ci/bin/make-it-executable.js
  packages/datadog-ci/package.json
  packages/datadog-ci/src/cli.ts
  packages/plugin-aas/package.json
  packages/plugin-cloud-run/package.json
  packages/plugin-deployment/package.json
  packages/plugin-dora/package.json
  packages/plugin-gate/package.json
  packages/plugin-lambda/package.json
  packages/plugin-sarif/package.json
  packages/plugin-sbom/package.json
  packages/plugin-stepfunctions/package.json
  packages/plugin-synthetics/package.json
Labels: chores

#1865 v3.21.1 (redo)
  packages/plugin-deployment/package.json
Labels: release

#1873 Fix git metadata import
  packages/base/package.json
  packages/datadog-ci/src/index.ts
Labels: bug, source-code-integration

#1881 [chore] Remove unused `--compress` flag for `pkg`
  package.json
Labels: chores
