Repository DataDog/datadog-ci, pull requests merged in 2025-07, with the labels that each got.

#1710 GCR Instrument improvements + additional instrument flags
  src/commands/cloud-run/__tests__/instrument.test.ts
  src/commands/cloud-run/instrument.ts
  src/commands/cloud-run/types.ts
  src/commands/lambda/__tests__/functions/commons.test.ts
  src/commands/lambda/__tests__/functions/instrument.part1.test.ts
  src/commands/lambda/__tests__/functions/uninstrument.test.ts
  src/commands/lambda/__tests__/uninstrument.test.ts
  src/commands/lambda/constants.ts
  src/commands/lambda/functions/instrument.ts
  src/commands/lambda/functions/uninstrument.ts
  src/commands/lambda/instrument.ts
  src/constants.ts
Labels: serverless

#1719 v3.12.0
  package.json
Labels: release

#1659 Print link to Datadog UI when uploading coverage data
  src/commands/coverage/renderer.ts
  src/commands/coverage/upload.ts
  src/commands/coverage/utils.ts
  src/commands/junit/utils.ts
  src/commands/sarif/renderer.ts
  src/commands/sbom/api.ts
  src/commands/sbom/renderer.ts
  src/helpers/app.ts
Labels: ci-visibility

#1721 yarn install step added to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1715 [SYNTH-20553] Add link to Test Optimization
  src/commands/junit/utils.ts
  src/commands/synthetics/__tests__/batch.test.ts
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/reporters/default.ts
  src/commands/synthetics/run-tests-lib.ts
Labels: synthetics

#1722 [Cloud Run Instrument] Dry run and interactive mode
  LICENSE-3rdparty.csv
  package.json
  src/commands/cloud-run/__tests__/__snapshots__/instrument.test.ts.snap
  src/commands/cloud-run/__tests__/instrument.test.ts
  src/commands/cloud-run/__tests__/utils.test.ts
  src/commands/cloud-run/instrument.ts
  src/commands/cloud-run/interfaces.ts
  src/commands/cloud-run/prompt.ts
  src/commands/cloud-run/renderer.ts
  src/commands/cloud-run/utils.ts
  yarn.lock
Labels: serverless

#1728 [Cloud Run Instrument] FIPs, source code integration, and customizable sidecar,shared-volume,logs-path
  src/commands/cloud-run/__tests__/__snapshots__/instrument.test.ts.snap
  src/commands/cloud-run/__tests__/instrument.test.ts
  src/commands/cloud-run/instrument.ts
  src/commands/lambda/__tests__/instrument.test.ts
  src/commands/lambda/instrument.ts
  src/helpers/git/instrument-helpers.ts
Labels: serverless

#1727 [SVLS-7097] add unified tags as resource tags
  LICENSE-3rdparty.csv
  package.json
  src/commands/aas/__tests__/common.ts
  src/commands/aas/__tests__/instrument.test.ts
  src/commands/aas/instrument.ts
  yarn.lock
Labels: enhancement, serverless

#1730 [SVLS-7098] aas instrument support arbitrary env vars
  src/commands/aas/__tests__/instrument.test.ts
  src/commands/aas/common.ts
  src/commands/aas/instrument.ts
  src/commands/aas/interfaces.ts
Labels: enhancement, serverless

#1731 [SYNTH-20802] Fix JUnit reporter not being initialized
  src/commands/synthetics/__tests__/base-command.test.ts
  src/commands/synthetics/base-command.ts
Labels: synthetics

#1739 Fix coverage upload dir scan to handle symlinks
  src/commands/coverage/__tests__/fixtures/random-file-symlink.xml
  src/commands/coverage/__tests__/upload.test.ts
  src/commands/coverage/upload.ts
  src/helpers/file-finder.ts
Labels: ci-visibility

#1723 Add fallback `DD_API_KEY`, `DD_APP_KEY` and `DD_SITE` to all commands
  src/commands/cloud-run/__tests__/__snapshots__/flare.test.ts.snap
  src/commands/cloud-run/__tests__/flare.test.ts
  src/commands/cloud-run/flare.ts
  src/commands/dsyms/README.md
  src/commands/dsyms/__tests__/upload.test.ts
  src/commands/dsyms/upload.ts
  src/commands/elf-symbols/README.md
  src/commands/elf-symbols/upload.ts
  src/commands/flutter-symbols/README.md
  src/commands/flutter-symbols/upload.ts
  src/commands/git-metadata/README.md
  src/commands/git-metadata/__tests__/upload.test.ts
  src/commands/git-metadata/upload.ts
  src/commands/lambda/__tests__/__snapshots__/flare.test.ts.snap
  src/commands/lambda/flare.ts
  src/commands/lambda/renderers/instrument-uninstrument-renderer.ts
  src/commands/pe-symbols/README.md
  src/commands/pe-symbols/upload.ts
  src/commands/react-native/README.md
  src/commands/react-native/__tests__/upload.test.ts
  src/commands/react-native/__tests__/xcode.test.ts
  src/commands/react-native/upload.ts
  src/commands/sarif/README.md
  src/commands/sourcemaps/README.md
  src/commands/sourcemaps/__tests__/upload.test.ts
  src/commands/sourcemaps/upload.ts
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/utils/__snapshots__/public.test.ts.snap
  src/commands/synthetics/base-command.ts
  src/commands/synthetics/examples/global-config-complete-example.json
  src/commands/synthetics/utils/public.ts
  src/commands/unity-symbols/README.md
  src/commands/unity-symbols/upload.ts
  src/helpers/apikey.ts
Labels: rum, synthetics, serverless, source-code-integration, static-analysis, profiling

#1743 Fix base SHA calculation for GitHub actions
  src/commands/coverage/upload.ts
Labels: ci-visibility

#1746 [Cloud Run] Enable and document instrument & uninstrument commands
  README.md
  src/commands/cloud-run/README.md
  src/commands/cloud-run/cli.ts
  src/commands/cloud-run/instrument.ts
  src/commands/cloud-run/uninstrument.ts
Labels: serverless

#1748 Fix LCOV coverage format validation
  src/commands/coverage/__tests__/fixtures/lcov-bazel.info
  src/commands/coverage/__tests__/upload.test.ts
  src/commands/coverage/__tests__/utils.test.ts
  src/commands/coverage/utils.ts
Labels: ci-visibility

#1749 v3.15.0
  package.json
Labels: release

#1750 Remove redundant log from coverage upload command
  src/commands/coverage/upload.ts
Labels: ci-visibility

#1759 Add `datadog-ci-admins` group to codeowners
  .github/CODEOWNERS
Labels: chores

#1753 [SVLS-7166] [AAS .NET] use glibc by default for the profiler path, with the option for musl
  src/commands/aas/__tests__/common.test.ts
  src/commands/aas/__tests__/instrument.test.ts
  src/commands/aas/common.ts
  src/commands/aas/instrument.ts
  src/commands/aas/interfaces.ts
Labels: enhancement, serverless

#1758 [chores] Add `datadog-ci` label for repo-wide changes
  .github/release.yml
  .github/workflows/pr-required-labels.yml
Labels: chores

#1760 Remove the `@DataDog/datadog-ci` from CODEOWNERS
  .github/CODEOWNERS
Labels: chores

#1757 [synthetics] Downgrade some tunnel warn logs to debug
  LICENSE-3rdparty.csv
  package.json
  src/commands/synthetics/README.md
  src/commands/synthetics/tunnel/tunnel.ts
  yarn.lock
Labels: synthetics

#1709 [SVLS-6823] Support FIPS-compatible lambda functions
  src/commands/lambda/README.md
  src/commands/lambda/__tests__/functions/commons.test.ts
  src/commands/lambda/__tests__/functions/instrument.part1.test.ts
  src/commands/lambda/__tests__/functions/instrument.part2.test.ts
  src/commands/lambda/__tests__/instrument.test.ts
  src/commands/lambda/constants.ts
  src/commands/lambda/functions/commons.ts
  src/commands/lambda/functions/instrument.ts
  src/commands/lambda/functions/uninstrument.ts
  src/commands/lambda/instrument.ts
  src/commands/lambda/interfaces.ts
Labels: enhancement, serverless

#1766 v3.16.0
  package.json
Labels: release

#1745 [SYNTH-19315] Add batch-smoke-tester to bump-ci-integrations list
  .github/workflows/publish-release.yml
Labels: chores

#1632 doc: improve `--auto-discovery` option docs
  src/commands/junit/README.md
Labels: documentation, ci-visibility

#1763 [synthetics] Support results without `subtype` in default reporter
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/reporters/default.ts
Labels: synthetics

#1768 [chores] Set `versioning-strategy: increase` for dependabot
  .github/dependabot.yml
Labels: chores

#1774 [SVLS] add ONE to flare helpers
  .github/CODEOWNERS
Labels: chores

#1762 Add retries to deployment gate command
  src/commands/deployment/__tests__/__snapshots__/gate.test.ts.snap
  src/commands/deployment/__tests__/gate.test.ts
  src/commands/deployment/gate.ts
Labels: ci-visibility

#1781 [coverage] Use `git.pull_request.base_branch_head_sha` instead of `git.pull_request.base_branch_sha` in GitHub Actions
  src/commands/coverage/upload.ts
  src/helpers/__tests__/ci.test.ts
  src/helpers/ci.ts
  src/helpers/interfaces.ts
  src/helpers/tags.ts
Labels: ci-visibility

#1790 [ci] Use github app token for release automation
  .github/workflows/publish-release.yml
Labels: chores

#1791 Bump dependencies to address `form-data` security findings
  package.json
  yarn.lock
Labels: dependencies

#1792 SYNTH-21051: Update CODEOWNERS -synthetics-ct/+synthetics-orchestrating
  .github/CODEOWNERS
Labels: chores
