Repository DataDog/datadog-ci, pull requests merged in 2025-04, with the labels that each got.

#1602 [Synthetics] Introduce BaseCommand
  src/commands/synthetics/__tests__/api.test.ts
  src/commands/synthetics/__tests__/batch.test.ts
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/deploy-tests-lib.test.ts
  src/commands/synthetics/__tests__/import-tests-lib.test.ts
  src/commands/synthetics/__tests__/test.test.ts
  src/commands/synthetics/__tests__/tunnel/websocket.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/api.ts
  src/commands/synthetics/base-command.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/deploy-tests-command.ts
  src/commands/synthetics/import-tests-command.ts
  src/commands/synthetics/index.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/test.ts
  src/commands/synthetics/upload-application-command.ts
  src/helpers/utils.ts
Labels: synthetics

#1601 [SYNTH-19229] Add error handling and unit tests to build-and-test
  src/commands/synthetics/__tests__/build-and-test.test.ts
  src/commands/synthetics/build-and-test.ts
Labels: synthetics

#1598 [K9VULN-3651] Automatically determine generation tool used from Sbom
  src/commands/sbom/__tests__/fixtures/cdxgen-cyclonedx1.6.json
  src/commands/sbom/__tests__/fixtures/sbom.1.4.ok-without-metadata.json
  src/commands/sbom/__tests__/fixtures/sbom.1.5.ok-with-tools-as-components.json
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/constants.ts
  src/commands/sbom/payload.ts
  src/commands/sbom/types.ts
  src/helpers/interfaces.ts
Labels: enhancement, static-analysis

#1607 [synthetics] Improve error handling in mobile upload command
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/upload-application-command.ts
Labels: synthetics

#1608 v3.3.0
  package.json
Labels: release

#1610 [sbom] Fix build issue with import
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/constants.ts
  src/commands/sbom/payload.ts
  src/helpers/interfaces.ts
  src/helpers/tags.ts
Labels: static-analysis

#1611 v3.3.1
  package.json
Labels: release

#1614 [RN CODEPUSH] Sanitize Upload Release Version
  src/commands/react-native/__tests__/codepush.test.ts
  src/commands/react-native/__tests__/fixtures/codepush-deployment-history/valid-deployment-with-invalid-version.txt
  src/commands/react-native/__tests__/fixtures/codepush-deployment-history/valid-deployment-with-prefix-symbols.txt
  src/commands/react-native/__tests__/utils.test.ts
  src/commands/react-native/codepush.ts
  src/commands/react-native/utils.ts
Labels: rum

#1599 [K9VULN-4382] Parse, validate, and propagate reachability info
  src/commands/sbom/__tests__/fixtures/sbom-with-reachability.json
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/__tests__/validation.test.ts
  src/commands/sbom/constants.ts
  src/commands/sbom/payload.ts
  src/commands/sbom/types.ts
Labels: static-analysis

#1604 chore: Improve error message for flare file upload
  src/helpers/__tests__/flare.test.ts
  src/helpers/flare.ts
Labels: chores

#1603 [MLOB-2522] Add `--llmobs` flag for instrumenting Lambdas with LLM Observability
  src/commands/lambda/README.md
  src/commands/lambda/__tests__/__snapshots__/instrument.test.ts.snap
  src/commands/lambda/__tests__/functions/instrument.part1.test.ts
  src/commands/lambda/__tests__/functions/instrument.part2.test.ts
  src/commands/lambda/__tests__/functions/uninstrument.test.ts
  src/commands/lambda/__tests__/instrument.test.ts
  src/commands/lambda/__tests__/uninstrument.test.ts
  src/commands/lambda/constants.ts
  src/commands/lambda/functions/instrument.ts
  src/commands/lambda/functions/uninstrument.ts
  src/commands/lambda/instrument.ts
  src/commands/lambda/interfaces.ts
Labels: documentation, serverless

#1615 [Synthetics] Redesign build-and-test command to spawn the dev server
  src/commands/synthetics/__tests__/build-and-test.test.ts
  src/commands/synthetics/build-and-test.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/utils/internal.ts
Labels: synthetics

#1616 Make code coverage upload command non-beta
  src/cli.ts
Labels: ci-visibility

#1580 [feature] Custom span command
  src/commands/span/README.md
  src/commands/span/__tests__/span.test.ts
  src/commands/span/cli.ts
  src/commands/span/span.ts
  src/commands/trace/__tests__/trace.test.ts
  src/commands/trace/helper.ts
  src/commands/trace/test-utils.ts
  src/commands/trace/trace.ts
Labels: enhancement, editorial review, ci-visibility

#1617 [SYNTH-19349] bump the batch timeout safety margin to 60s
  src/commands/synthetics/__tests__/batch.test.ts
  src/commands/synthetics/batch.ts
Labels: synthetics

#1618 Release v3.4.0
  package.json
Labels: synthetics, release

#1620 [chores] Fix lint and `.gitignore` file
  .eslintrc.js
  .gitignore
  package.json
Labels: chores

#1622 [test] Simplify unit tests with new helpers
  .eslintrc.js
  .gitignore
  src/cli.ts
  src/commands/cloud-run/__tests__/__snapshots__/flare.test.ts.snap
  src/commands/cloud-run/__tests__/fixtures.ts
  src/commands/cloud-run/__tests__/flare.test.ts
  src/commands/coverage/__tests__/upload.test.ts
  src/commands/deployment/__tests__/correlate.test.ts
  src/commands/deployment/__tests__/mark.test.ts
  src/commands/dora/__tests__/deployment.test.ts
  src/commands/dsyms/__tests__/upload.test.ts
  src/commands/elf-symbols/__tests__/upload.test.ts
  src/commands/flutter-symbols/__tests__/upload.test.ts
  src/commands/gate/__tests__/evaluate.test.ts
  src/commands/git-metadata/__tests__/upload.test.ts
  src/commands/junit/__tests__/upload.test.ts
  src/commands/lambda/__tests__/__snapshots__/flare.test.ts.snap
  src/commands/lambda/__tests__/__snapshots__/uninstrument.test.ts.snap
  src/commands/lambda/__tests__/fixtures.ts
  src/commands/lambda/__tests__/flare.test.ts
  src/commands/lambda/__tests__/functions/commons.test.ts
  src/commands/lambda/__tests__/functions/instrument.part2.test.ts
  src/commands/lambda/__tests__/instrument.test.ts
  src/commands/lambda/__tests__/prompt.test.ts
  src/commands/lambda/__tests__/uninstrument.test.ts
  src/commands/measure/__tests__/measure.test.ts
  src/commands/react-native/__tests__/codepush.test.ts
  src/commands/react-native/__tests__/upload.test.ts
  src/commands/react-native/__tests__/xcode.test.ts
  src/commands/sarif/__tests__/upload.test.ts
  src/commands/sourcemaps/__tests__/upload.test.ts
  src/commands/span/__tests__/span.test.ts
  src/commands/stepfunctions/__tests__/awsCommands.test.ts
  src/commands/stepfunctions/__tests__/fixtures/cli.ts
  src/commands/stepfunctions/__tests__/instrument.test.ts
  src/commands/stepfunctions/__tests__/uninstrument.test.ts
  src/commands/synthetics/__tests__/api.test.ts
  src/commands/synthetics/__tests__/batch.test.ts
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/__tests__/reporters/junit.test.ts
  src/commands/synthetics/__tests__/reporters/mobile/__snapshots__/app-upload.test.ts.snap
  src/commands/synthetics/__tests__/reporters/mobile/app-upload.test.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/test.test.ts
  src/commands/synthetics/__tests__/tunnel/websocket.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/tag/__tests__/tag.test.ts
  src/commands/trace/__tests__/trace.test.ts
  src/commands/trace/test-utils.ts
  src/commands/unity-symbols/__tests__/upload.test.ts
  src/helpers/__tests__/flare.test.ts
  src/helpers/__tests__/fs.test.ts
  src/helpers/__tests__/testing-tools.ts
  src/helpers/__tests__/utils.test.ts
  src/helpers/interfaces.ts
Labels: chores

#1623 [lint] Add `jest/padding-around-test-blocks` eslint rule
  .eslintrc.js
  package.json
  src/commands/deployment/__tests__/correlate.test.ts
  src/commands/deployment/__tests__/mark.test.ts
  src/commands/dora/__tests__/deployment.test.ts
  src/commands/elf-symbols/__tests__/elf.test.ts
  src/commands/gate/__tests__/evaluate.test.ts
  src/commands/gate/__tests__/scope.test.ts
  src/commands/git-metadata/__tests__/git.test.ts
  src/commands/junit/__tests__/upload.test.ts
  src/commands/lambda/__tests__/flare.test.ts
  src/commands/lambda/__tests__/functions/commons.test.ts
  src/commands/lambda/__tests__/functions/instrument.part1.test.ts
  src/commands/lambda/__tests__/functions/instrument.part2.test.ts
  src/commands/lambda/__tests__/functions/uninstrument.test.ts
  src/commands/lambda/__tests__/instrument.test.ts
  src/commands/lambda/__tests__/loggroup.test.ts
  src/commands/lambda/__tests__/prompt.test.ts
  src/commands/lambda/__tests__/tags.test.ts
  src/commands/lambda/__tests__/uninstrument.test.ts
  src/commands/react-native/__tests__/utils.test.ts
  src/commands/sarif/__tests__/upload.test.ts
  src/commands/sarif/__tests__/utils.test.ts
  src/commands/sarif/__tests__/validation.test.ts
  src/commands/sbom/__tests__/validation.test.ts
  src/commands/span/__tests__/span.test.ts
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/multilocator.test.ts
  src/commands/synthetics/__tests__/utils/internal.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/trace/__tests__/trace.test.ts
  src/commands/trace/test-utils.ts
  src/helpers/__tests__/ci.test.ts
  src/helpers/__tests__/fs.test.ts
  src/helpers/__tests__/plist.test.ts
  src/helpers/__tests__/prompt.test.ts
  src/helpers/__tests__/tags.test.ts
  src/helpers/__tests__/user-provided-git.test.ts
  src/helpers/git/__tests__/format-git-sourcemaps-data.test.ts
  src/helpers/git/__tests__/format-git-span-data.test.ts
  src/helpers/git/__tests__/get-git-data.test.ts
  yarn.lock
Labels: chores

#1621 [SYNTH-18941] Use v1 results
  src/commands/synthetics/__tests__/api.test.ts
  src/commands/synthetics/__tests__/batch.test.ts
  src/commands/synthetics/__tests__/deploy-tests-lib.test.ts
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/multilocator.test.ts
  src/commands/synthetics/__tests__/reporters/__snapshots__/default.test.ts.snap
  src/commands/synthetics/__tests__/reporters/default.test.ts
  src/commands/synthetics/__tests__/reporters/junit.test.ts
  src/commands/synthetics/__tests__/test.test.ts
  src/commands/synthetics/api.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/multilocator.ts
  src/commands/synthetics/reporters/default.ts
  src/commands/synthetics/reporters/junit.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1628 [chores] Fix flaky retry unit tests
  src/commands/synthetics/__tests__/utils/public.test.ts
Labels: chores
