Repository DataDog/datadog-ci, pull requests merged in 2025-06, with the labels that each got.

#1662 Upload git metadata when uploading coverage
  src/commands/coverage/README.md
  src/commands/coverage/__tests__/upload.test.ts
  src/commands/coverage/renderer.ts
  src/commands/coverage/upload.ts
Labels: ci-visibility

#1664 [SYNTH-20250] Add exclude-field option for deploy command
  LICENSE-3rdparty.csv
  package.json
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/deploy-tests-lib.test.ts
  src/commands/synthetics/deploy-tests-command.ts
  src/commands/synthetics/deploy-tests-lib.ts
  src/commands/synthetics/interfaces.ts
  yarn.lock
Labels: synthetics

#1661 Add current folder as a safe.directory in git config
  src/commands/git-metadata/git.ts
Labels: ci-visibility

#1666 Implement getting PR info tags from CI providers
  src/commands/coverage/upload.ts
  src/commands/gate/evaluate.ts
  src/commands/git-metadata/git.ts
  src/helpers/__tests__/ci-env/appveyor.json
  src/helpers/__tests__/ci-env/azurepipelines.json
  src/helpers/__tests__/ci-env/bitbucket.json
  src/helpers/__tests__/ci-env/bitrise.json
  src/helpers/__tests__/ci-env/buddy.json
  src/helpers/__tests__/ci-env/buildkite.json
  src/helpers/__tests__/ci-env/circleci.json
  src/helpers/__tests__/ci-env/codefresh.json
  src/helpers/__tests__/ci-env/drone.json
  src/helpers/__tests__/ci-env/github.json
  src/helpers/__tests__/ci-env/gitlab.json
  src/helpers/__tests__/ci-env/jenkins.json
  src/helpers/__tests__/ci-env/teamcity.json
  src/helpers/__tests__/ci-env/travisci.json
  src/helpers/__tests__/ci-env/usersupplied.json
  src/helpers/__tests__/ci.test.ts
  src/helpers/__tests__/user-provided-git.test.ts
  src/helpers/ci.ts
  src/helpers/interfaces.ts
  src/helpers/tags.ts
  src/helpers/user-provided-git.ts
Labels: ci-visibility

#1670 Use `moduleResolution: node16` and remove `baseUrl`
  src/commands/synthetics/__tests__/reporters/mobile/app-upload.test.ts
  tsconfig.json
  yarn.lock
Labels: chores

#1669 [K9VULN-5794] Guard against vulnerabilities without affects being defined
  src/commands/sbom/__tests__/fixtures/sbom-with-reachability.json
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/payload.ts
Labels: static-analysis

#1654 feat(SYNTH-20126): Add AP2 as possible datacenter
  src/commands/cloud-run/README.md
  src/commands/gate/__tests__/evaluate.test.ts
  src/commands/lambda/README.md
  src/commands/lambda/__tests__/functions/instrument.part2.test.ts
  src/commands/lambda/functions/instrument.ts
  src/commands/react-native/README.md
  src/constants.ts
  src/helpers/__tests__/__snapshots__/flare.test.ts.snap
  src/helpers/__tests__/app.test.ts
  src/helpers/__tests__/validation.test.ts
Labels: chores

#1673 [SVLS-6923] fix sidecar application settings
  src/commands/aas/__tests__/instrument.test.ts
  src/commands/aas/instrument.ts
Labels: bug, serverless

#1675 [chore] improve test coverage of helper methods
  src/commands/aas/__tests__/instrument.test.ts
  src/commands/aas/instrument.ts
Labels: serverless, chores

#1678 [SVLS-7006] add api key validation
  src/commands/aas/__tests__/instrument.test.ts
  src/commands/aas/instrument.ts
  src/helpers/__tests__/upload.test.ts
  src/helpers/apikey.ts
Labels: enhancement, serverless

#1686 Fix `git` logic in `coverage upload` command
  src/commands/coverage/upload.ts
Labels: bug, ci-visibility

#1685 v3.9.0
  package.json
Labels: release

#1687 Support uploading opencover coverage reports
  src/commands/coverage/__tests__/fixtures/subfolder.xml/opencover-coverage-invalid.xml
  src/commands/coverage/__tests__/fixtures/subfolder.xml/opencover-coverage-malformed.xml
  src/commands/coverage/__tests__/fixtures/subfolder.xml/opencover-coverage.xml
  src/commands/coverage/__tests__/upload.test.ts
  src/commands/coverage/__tests__/utils.test.ts
  src/commands/coverage/utils.ts
Labels: ci-visibility

#1680 [K9VULN-5872] Send exclusion properties as a dependency field
  src/commands/sbom/__tests__/fixtures/sbom-with-exclusion.json
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/__tests__/validation.test.ts
  src/commands/sbom/constants.ts
  src/commands/sbom/payload.ts
  src/commands/sbom/types.ts
Labels: enhancement, static-analysis

#1693 [SVLS-7005] aas instrument dotnet settings support
  src/commands/aas/__tests__/common.test.ts
  src/commands/aas/__tests__/instrument.test.ts
  src/commands/aas/common.ts
  src/commands/aas/instrument.ts
  src/commands/aas/interfaces.ts
Labels: enhancement, serverless

#1688 [SYNTH-20482] Mark `/w` as safe in docker image entrypoint
  README.md
  container/Dockerfile
  container/entrypoint.sh
Labels: source-code-integration

#1697 Upload RN sourcemaps with debug-id
  src/commands/react-native/__tests__/fixtures/sourcemap-with-debug-id/bundle.min.js
  src/commands/react-native/__tests__/fixtures/sourcemap-with-debug-id/bundle.min.js.map
  src/commands/react-native/__tests__/interfaces.test.ts
  src/commands/react-native/__tests__/upload.test.ts
  src/commands/react-native/interfaces.ts
  src/commands/react-native/upload.ts
Labels: enhancement, rum, javascript

#1700 [dep] Upgrade form-data to `4.0.3`
  package.json
  yarn.lock
Labels: dependencies

#1708 [chore] Bump `@google-cloud/run` to v2
  package.json
  src/commands/cloud-run/__tests__/instrument.test.ts
  src/commands/cloud-run/flare.ts
  src/commands/cloud-run/instrument.ts
  src/commands/cloud-run/types.ts
  yarn.lock
Labels: serverless, chores
