Repository DataDog/datadog-ci, pull requests merged in 2025-10, with the labels that each got.

#1888 Release dora command
  packages/datadog-ci/README.md
  packages/datadog-ci/src/cli.ts
  packages/plugin-dora/README.md
Labels: software-delivery

#1889 Add hint about --fail-on-error param on deployment gate unexpected failures
  packages/plugin-deployment/src/__tests__/__snapshots__/gate.test.ts.snap
  packages/plugin-deployment/src/commands/gate.ts
Labels: software-delivery

#1853 [K9VULN-7903] SARIF upload pull request err msg
  packages/plugin-sarif/src/__tests__/upload.test.ts
  packages/plugin-sarif/src/commands/upload.ts
Labels: static-analysis

#1890 [chore] Add notice for next major release
  packages/base/src/helpers/plugin.ts
Labels: chores, guild-project

#1891 [breaking] Drop `aas`, `cloud-run`, `lambda`, `stepfunctions` and `synthetics` plugins
  MIGRATING.md
  bin/lint-packages.ts
  container/Dockerfile
  packages/base/src/helpers/plugin.ts
  packages/datadog-ci/README.md
  packages/datadog-ci/package.json
  packages/datadog-ci/src/index.ts
  packages/datadog-ci/tsconfig.json
  packages/plugin-synthetics/README.md
  packages/plugin-synthetics/package.json
  yarn.lock
Labels: Do Not Merge, chores, guild-project

#1899 Revert "Merge pull request #1891 from DataDog/corentin.girard/SYNTH-2…
  MIGRATING.md
  bin/lint-packages.ts
  container/Dockerfile
  packages/base/src/helpers/plugin.ts
  packages/datadog-ci/README.md
  packages/datadog-ci/package.json
  packages/datadog-ci/src/index.ts
  packages/datadog-ci/tsconfig.json
  packages/plugin-synthetics/README.md
  packages/plugin-synthetics/package.json
  yarn.lock
Labels: chores

#1900 v3.22.1
  packages/base/package.json
  packages/datadog-ci/package.json
  packages/plugin-aas/package.json
  packages/plugin-cloud-run/package.json
  packages/plugin-deployment/package.json
  packages/plugin-dora/package.json
  packages/plugin-gate/package.json
  packages/plugin-lambda/package.json
  packages/plugin-sarif/package.json
  packages/plugin-sbom/package.json
  packages/plugin-stepfunctions/package.json
  packages/plugin-synthetics/package.json
Labels: release
