Repository DataDog/datadog-ci, pull requests merged in 2025-02, with the labels that each got.

#1533 Update docs for dSYMs and flutter-symbols
  src/commands/dsyms/README.md
  src/commands/flutter-symbols/README.md
Labels: documentation

#1535 [SYNTH-18215] Save multilocator in ltd
  src/commands/synthetics/__tests__/multilocator.test.ts
  src/commands/synthetics/errors.ts
  src/commands/synthetics/import-tests-lib.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/multilocator.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1538 [chores] Replace `metric` by `measure` in codeowners
  .github/CODEOWNERS
Labels: chores

#1539 Add quiet option to sourcemap upload
  src/commands/sourcemaps/README.md
  src/commands/sourcemaps/upload.ts
Labels: rum

#1549 add missing unit tests for resourceUrlSubstitutionRegexes
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
Labels: synthetics

#1521 [SYNTH-17719] Command to deploy LTDs
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/deploy-tests-config-with-all-keys.json
  src/commands/synthetics/__tests__/deploy-tests-lib.test.ts
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/api.ts
  src/commands/synthetics/cli.ts
  src/commands/synthetics/deploy-tests-command.ts
  src/commands/synthetics/deploy-tests-lib.ts
  src/commands/synthetics/import-tests-lib.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/local-test-definition.ts
  src/commands/synthetics/multilocator.ts
  src/commands/synthetics/test.ts
Labels: synthetics

#1543 [SYNTH-12989] Unexport public utils needing `APIHelper`
  src/commands/synthetics/__tests__/__snapshots__/test.test.ts.snap
  src/commands/synthetics/__tests__/batch.test.ts
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/test.test.ts
  src/commands/synthetics/__tests__/utils/__snapshots__/public.test.ts.snap
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/test.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1520 Add code coverage upload command
  src/cli.ts
  src/commands/coverage/README.md
  src/commands/coverage/__tests__/fixtures/another-jacoco-report.xml
  src/commands/coverage/__tests__/fixtures/invalid-jacoco-report.xml
  src/commands/coverage/__tests__/fixtures/jacoco-report.xml
  src/commands/coverage/__tests__/fixtures/non-xml-file.txt
  src/commands/coverage/__tests__/fixtures/random-file.xml
  src/commands/coverage/__tests__/fixtures/subfolder/nested-jacoco-report.xml
  src/commands/coverage/__tests__/upload.test.ts
  src/commands/coverage/__tests__/utils.test.ts
  src/commands/coverage/api.ts
  src/commands/coverage/cli.ts
  src/commands/coverage/interfaces.ts
  src/commands/coverage/renderer.ts
  src/commands/coverage/upload.ts
  src/commands/coverage/utils.ts
  src/commands/junit/__tests__/upload.test.ts
  src/commands/junit/upload.ts
  src/helpers/__tests__/id.test.ts
  src/helpers/id.ts
Labels: ci-visibility

#1550 [synthetics] add README.md documentation for resourceUrlSubstitutionRegexes
  src/commands/synthetics/README.md
Labels: documentation

#1551 use simpler substitution format
  src/commands/synthetics/README.md
Labels: documentation

#1552 Add fips options to code coverage command
  src/__tests__/cli.test.ts
  src/commands/coverage/upload.ts
Labels: ci-visibility

#1553 [chores] Update codeowners, docs, issue labeler
  .github/CODEOWNERS
  .github/advanced-issue-labeler.yml
  README.md
  src/commands/coverage/README.md
Labels: chores

#1544 [SYNTH-12989] Remove deprecated CLI parameters
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
  src/commands/synthetics/__tests__/config-fixtures/config-with-global-polling-timeout.json
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/reporters/junit.test.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/batch.ts
  src/commands/synthetics/compatibility.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/reporters/junit.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/run-tests-lib.ts
  src/commands/synthetics/test.ts
  src/commands/synthetics/utils/internal.ts
  src/commands/synthetics/utils/public.ts
Labels: synthetics

#1555 [ci] Fix slow `getSyntheticsOrgSettings` unit test
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/utils/public.ts
Labels: chores

#1554 Drop support for Node 14 and 16
  .github/workflows/ci.yml
  .github/workflows/publish-prerelease.yml
  .github/workflows/publish-release.yml
  package.json
Labels: chores

#1545 [SYNTH-12989] Remove `global` object in global config file
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/test.test.ts
  src/commands/synthetics/compatibility.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/run-tests-lib.ts
Labels: synthetics

#1546 [SYNTH-12989] Remove `config` object in test files
  .github/workflows/e2e/tests.synthetics.json
  src/commands/synthetics/README.md
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/fixtures.ts
  src/commands/synthetics/__tests__/run-tests-lib.test.ts
  src/commands/synthetics/__tests__/test.test.ts
  src/commands/synthetics/compatibility.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/reporters/junit.ts
  src/commands/synthetics/test.ts
Labels: synthetics

#1548 [SYNTH-12989] Remove deprecated `files` usage
  src/commands/synthetics/run-tests-command.ts
Labels: synthetics

#1560 [dep] Drop rimraf in production code
  LICENSE-3rdparty.csv
  package.json
  src/commands/dsyms/utils.ts
  yarn.lock
Labels: dependencies

#1559 [dep] Bump glob to `10.4.5`
  package.json
  src/commands/coverage/__tests__/upload.test.ts
  src/commands/coverage/upload.ts
  src/commands/dsyms/__tests__/upload.test.ts
  src/commands/dsyms/__tests__/utils.test.ts
  src/commands/dsyms/upload.ts
  src/commands/elf-symbols/upload.ts
  src/commands/flutter-symbols/__tests__/upload.test.ts
  src/commands/flutter-symbols/upload.ts
  src/commands/junit/__tests__/upload.test.ts
  src/commands/junit/upload.ts
  src/commands/sarif/__tests__/upload.test.ts
  src/commands/sarif/upload.ts
  src/commands/sourcemaps/upload.ts
  src/commands/synthetics/__tests__/utils/public.test.ts
  src/commands/synthetics/utils/public.ts
  src/commands/unity-symbols/upload.ts
  yarn.lock
Labels: dependencies

#1562 [ci] Bump dd-trace to `5.38.0`
  package.json
  yarn.lock
Labels: chores

#1537 [lambda] Add support for Node.js 22 and Python 3.13
  package.json
  src/commands/lambda/__tests__/__snapshots__/instrument.test.ts.snap
  src/commands/lambda/__tests__/instrument.test.ts
  src/commands/lambda/constants.ts
  yarn.lock
Labels: serverless

#1563 [docs] Add migration guide for major version `3.0`
  MIGRATING.md
  README.md
Labels: documentation

#1564 v3.0.0
  package.json
Labels: release

#1566 [SYNTH-18686] Hotfix: only prompt ml updates if config contains ltds
  src/commands/synthetics/run-tests-lib.ts
Labels: bug, synthetics

#1569 [K9VULN-3897] Filter large SARIF files
  src/commands/sarif/renderer.ts
  src/commands/sarif/validation.ts
Labels: bug, static-analysis
