Repository DataDog/datadog-ci, pull requests merged in 2025-03, with the labels that each got.

#1571 add service from the SARIF file
  src/commands/sarif/__tests__/fixtures/datadog-sa-only.json
  src/commands/sarif/__tests__/fixtures/datadog-sa-secrets.json
  src/commands/sarif/__tests__/fixtures/datadog-secrets-only-empty.json
  src/commands/sarif/__tests__/utils.test.ts
  src/commands/sarif/api.ts
  src/commands/sarif/interfaces.ts
  src/commands/sarif/upload.ts
  src/commands/sarif/utils.ts
  src/commands/sarif/validation.ts
Labels: static-analysis

#1572 v3.0.2
  package.json
Labels: release

#1574 [lambda] support `ruby3.3` and `provided.al2023`
  src/commands/lambda/__tests__/__snapshots__/instrument.test.ts.snap
  src/commands/lambda/__tests__/instrument.test.ts
  src/commands/lambda/constants.ts
Labels: serverless

#1575 [lambda] [bugfix] Ensure ARM layers are used for python3.13 ARM functions
  src/commands/lambda/__tests__/functions/instrument.part2.test.ts
  src/commands/lambda/constants.ts
Labels: serverless

#1576 bump file size for SARIF file
  src/commands/sarif/validation.ts
Labels: static-analysis

#1582 v3.1.0
  package.json
Labels: release

#1568 [SYNTH-18694] Do not prompt ML update confirmation in CI environments
  src/commands/synthetics/__tests__/multilocator.test.ts
  src/commands/synthetics/multilocator.ts
  src/helpers/__tests__/ci.test.ts
  src/helpers/ci.ts
  src/helpers/prompt.ts
Labels: synthetics

#1585 [SDTEST-1714] Add Drone CI support
  src/helpers/__tests__/ci-env/drone.json
  src/helpers/ci.ts
Labels: ci-visibility

#1586 Implement logic to automatically discover code coverage and jUnit XML report files
  src/commands/coverage/README.md
  src/commands/coverage/__tests__/fixtures/jacoco-report-incorrect-root-tag.xml
  src/commands/coverage/__tests__/fixtures/other-Jacoco-report.xml
  src/commands/coverage/__tests__/fixtures/subfolder.xml/nested-Jacoco-report.xml
  src/commands/coverage/__tests__/upload.test.ts
  src/commands/coverage/__tests__/utils.test.ts
  src/commands/coverage/renderer.ts
  src/commands/coverage/upload.ts
  src/commands/coverage/utils.ts
  src/commands/junit/README.md
  src/commands/junit/__tests__/fixtures/autodiscovery/junit-report.xml
  src/commands/junit/__tests__/fixtures/autodiscovery/nested/TEST-suite.xml
  src/commands/junit/__tests__/fixtures/autodiscovery/regular-file.xml
  src/commands/junit/__tests__/fixtures/autodiscovery/test-results.xml
  src/commands/junit/__tests__/upload.test.ts
  src/commands/junit/renderer.ts
  src/commands/junit/upload.ts
  src/commands/junit/utils.ts
  src/helpers/file-finder.ts
  src/helpers/tags.ts
  src/helpers/utils.ts
Labels: ci-visibility

#1590 Bump `dd-trace` to `^5.42.0`
  package.json
  yarn.lock
Labels: dependencies

#1570 [K9VULN-3872] Add --git-repository option to sbom/sarif upload
  src/commands/sarif/README.md
  src/commands/sarif/__tests__/fixtures/gitconfig
  src/commands/sarif/__tests__/upload.test.ts
  src/commands/sarif/renderer.ts
  src/commands/sarif/upload.ts
  src/commands/sbom/README.md
  src/commands/sbom/__tests__/fixtures/gitconfig
  src/commands/sbom/__tests__/payload.test.ts
  src/commands/sbom/upload.ts
  src/helpers/__tests__/tags.test.ts
  src/helpers/git/format-git-span-data.ts
  src/helpers/tags.ts
Labels: documentation, enhancement

#1591 v3.2.0
  package.json
Labels: release

#1579 Fix upload of ELF dynamic symbols
  src/commands/elf-symbols/README.md
  src/commands/elf-symbols/__tests__/elf.test.ts
  src/commands/elf-symbols/__tests__/fixtures/dyn_x86_64
  src/commands/elf-symbols/__tests__/upload.test.ts
  src/commands/elf-symbols/elf.ts
  src/commands/elf-symbols/upload.ts
Labels: bug, profiling

#1595 implement the build-and-test command
  src/commands/synthetics/__tests__/build-and-test.test.ts
  src/commands/synthetics/__tests__/cli.test.ts
  src/commands/synthetics/__tests__/config-fixtures/config-with-all-keys.json
  src/commands/synthetics/build-and-test.ts
  src/commands/synthetics/interfaces.ts
  src/commands/synthetics/run-tests-command.ts
  src/commands/synthetics/utils/internal.ts
Labels: synthetics
